Fix: Create asset of correct class type (#16363) (#18439)
Error: `Asset::create(data: ['type' => 'folder'])` returned a `\Pimcore\Model\Asset\Unknown` instead of `\Pimcore\Model\Asset\Folder`
Caused by: The type was only used when detected by the binary file data
Resolved with: Adding a type check on the $data array

Resolves #16363